// PRODUCTION/PRODUCTION_2/src/lib/components/ui/Card.svelte
<script lang="ts">
	export let padding: 'none' | 'sm' | 'md' | 'lg' = 'md';

	const paddingStyles = {
		none: '',
		sm: 'p-4',
		md: 'p-6',
		lg: 'p-8'
	};

	$: classes = `bg-white rounded-xl shadow-lg border border-gray-200 ${paddingStyles[padding]} ${$$props.class || ''}`;
</script>

<div class={classes}>
	<slot />
</div>

// PRODUCTION/PRODUCTION_1/components/ui/Card.tsx
import React from 'react';

interface CardProps {
  children: React.ReactNode;
  className?: string;
  padding?: 'none' | 'sm' | 'md' | 'lg';
}

export function Card({ children, className = '', padding = 'md' }: CardProps) {
  const paddingStyles = {
    none: '',
    sm: 'p-4',
    md: 'p-6',
    lg: 'p-8',
  };
  
  return (
    <div className={`bg-white rounded-xl shadow-lg border border-gray-200 ${paddingStyles[padding]} ${className}`}>
      {children}
    </div>
  );
}
