// PRODUCTION/PRODUCTION_2/src/lib/components/wallet/CreateWalletModal.svelte
<script lang="ts">
	import { toast } from 'svelte-french-toast';
	import Modal from '../ui/Modal.svelte';
	import Input from '../ui/Input.svelte';
	import Button from '../ui/Button.svelte';
	import Alert from '../ui/Alert.svelte';
	import { createEthereumWallet } from '$lib/utils/ethereum';
	import { createBitcoinWallet } from '$lib/utils/bitcoin';
	import { walletStore } from '$lib/stores/walletStore';

	export let isOpen = false;

	let step: 'password' | 'mnemonic' = 'password';
	let password = '';
	let confirmPassword = '';
	let showPassword = false;
	let mnemonic = '';
	let error = '';
	let copied = false;

	function handlePasswordSubmit(e: Event) {
		e.preventDefault();
		error = '';

		if (password.length < 8) {
			error = 'Password must be at least 8 characters';
			return;
		}

		if (password !== confirmPassword) {
			error = 'Passwords do not match';
			return;
		}

		// Generate wallets
		const ethWallet = createEthereumWallet();
		const btcWallet = createBitcoinWallet();

		// Use the same mnemonic for both
		mnemonic = ethWallet.mnemonic;

		// Store wallet
		walletStore.createWallet(
			ethWallet.mnemonic,
			password,
			ethWallet.address,
			ethWallet.privateKey,
			btcWallet.address,
			btcWallet.privateKey
		);

		step = 'mnemonic';
	}

	async function copyMnemonic() {
		await navigator.clipboard.writeText(mnemonic);
		copied = true;
		toast.success('Recovery phrase copied!');
		setTimeout(() => (copied = false), 2000);
	}

	function handleComplete() {
		password = '';
		confirmPassword = '';
		mnemonic = '';
		step = 'password';
		isOpen = false;
	}
</script>

<Modal bind:isOpen title="Create New Wallet">
	{#if step === 'password'}
		<form on:submit={handlePasswordSubmit} class="space-y-4">
			{#if error}
				<Alert type="error" message={error} />
			{/if}

			<Alert
				type="info"
				message="Your password encrypts your wallet on this device. Choose a strong password you won't forget."
			/>

			<div class="relative">
				<Input
					type={showPassword ? 'text' : 'password'}
					label="Password"
					bind:value={password}
					required
					placeholder="Enter a strong password"
				/>
				<button
					type="button"
					on:click={() => (showPassword = !showPassword)}
					class="absolute right-3 top-9 text-gray-500"
				>
					{#if showPassword}
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"
							/>
						</svg>
					{:else}
						<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
							/>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
							/>
						</svg>
					{/if}
				</button>
			</div>

			<Input
				type={showPassword ? 'text' : 'password'}
				label="Confirm Password"
				bind:value={confirmPassword}
				required
				placeholder="Confirm your password"
			/>

			<Button type="submit" class="w-full">Create Wallet</Button>
		</form>
	{:else if step === 'mnemonic'}
		<div class="space-y-4">
			<Alert
				type="warning"
				message="Write down your recovery phrase and store it safely. You'll need it to recover your wallet."
			/>

			<div class="bg-gray-50 p-4 rounded-lg border-2 border-gray-200">
				<p class="text-sm text-gray-600 mb-2 font-semibold">Recovery Phrase</p>
				<p class="text-base font-mono text-gray-900 leading-relaxed">
					{mnemonic}
				</p>
			</div>

			<Button on:click={copyMnemonic} variant="outline" class="w-full">
				<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
					/>
				</svg>
				{copied ? 'Copied!' : 'Copy to Clipboard'}
			</Button>

			<Alert
				type="error"
				message="Never share your recovery phrase with anyone. Anyone with this phrase can access your funds."
			/>

			<Button on:click={handleComplete} class="w-full">I've Saved My Recovery Phrase</Button>
		</div>
	{/if}
</Modal>

// PRODUCTION/PRODUCTION_1/components/wallet/CreateWalletModal.tsx
import React, { useState } from 'react';
import { Modal } from '../ui/Modal';
import { Input } from '../ui/Input';
import { Button } from '../ui/Button';
import { Alert } from '../ui/Alert';
import { createEthereumWallet } from '@/lib/wallet/ethereum';
import { createBitcoinWallet } from '@/lib/wallet/bitcoin';
import { useWalletStore } from '@/lib/store/wallet-store';
import { Copy, Eye, EyeOff } from 'lucide-react';
import toast from 'react-hot-toast';

interface CreateWalletModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function CreateWalletModal({ isOpen, onClose }: CreateWalletModalProps) {
  const [step, setStep] = useState<'password' | 'mnemonic'>('password');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [mnemonic, setMnemonic] = useState('');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  
  const createWallet = useWalletStore((state) => state.createWallet);
  
  const handlePasswordSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    
    if (password.length < 8) {
      setError('Password must be at least 8 characters');
      return;
    }
    
    if (password !== confirmPassword) {
      setError('Passwords do not match');
      return;
    }
    
    // Generate wallets
    const ethWallet = createEthereumWallet();
    const btcWallet = createBitcoinWallet();

    // Use the same mnemonic for both (in production, you'd use the same seed)
    setMnemonic(ethWallet.mnemonic);

    // Store wallet with private keys
    createWallet(
      ethWallet.mnemonic,
      password,
      ethWallet.address,
      ethWallet.privateKey,
      btcWallet.address,
      btcWallet.privateKey
    );
    
    setStep('mnemonic');
  };
  
  const copyMnemonic = () => {
    navigator.clipboard.writeText(mnemonic);
    setCopied(true);
    toast.success('Recovery phrase copied!');
    setTimeout(() => setCopied(false), 2000);
  };
  
  const handleComplete = () => {
    setPassword('');
    setConfirmPassword('');
    setMnemonic('');
    setStep('password');
    onClose();
  };
  
  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Create New Wallet">
      {step === 'password' && (
        <form onSubmit={handlePasswordSubmit} className="space-y-4">
          {error && <Alert type="error" message={error} />}
          
          <Alert 
            type="info" 
            message="Your password encrypts your wallet on this device. Choose a strong password you won't forget."
          />
          
          <div className="relative">
            <Input
              type={showPassword ? 'text' : 'password'}
              label="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              placeholder="Enter a strong password"
            />
            <button
              type="button"
              onClick={() => setShowPassword(!showPassword)}
              className="absolute right-3 top-9 text-gray-500"
            >
              {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
            </button>
          </div>
          
          <Input
            type={showPassword ? 'text' : 'password'}
            label="Confirm Password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            required
            placeholder="Confirm your password"
          />
          
          <Button type="submit" className="w-full">
            Create Wallet
          </Button>
        </form>
      )}
      
      {step === 'mnemonic' && (
        <div className="space-y-4">
          <Alert 
            type="warning" 
            message="Write down your recovery phrase and store it safely. You'll need it to recover your wallet."
          />
          
          <div className="bg-gray-50 p-4 rounded-lg border-2 border-gray-200">
            <p className="text-sm text-gray-600 mb-2 font-semibold">Recovery Phrase</p>
            <p className="text-base font-mono text-gray-900 leading-relaxed">
              {mnemonic}
            </p>
          </div>
          
          <Button
            onClick={copyMnemonic}
            variant="outline"
            className="w-full"
          >
            <Copy size={16} className="mr-2" />
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </Button>
          
          <Alert 
            type="error" 
            message="Never share your recovery phrase with anyone. Anyone with this phrase can access your funds."
          />
          
          <Button onClick={handleComplete} className="w-full">
            I've Saved My Recovery Phrase
          </Button>
        </div>
      )}
    </Modal>
  );
}
